services:
  php-fpm:
    build:
      context: ./back
      target: base
    env_file:
      - ./back/.env.dist
    environment:
      - DB_NAME=${DB_NAME:-roadie}
      - DB_USER=${DB_USER:-app}
      - DB_PASSWORD=${DB_PASSWORD:-!ChangeMe!}
      - DB_PORT=${DB_PORT:-5432}
      - DB_HOST=database
      - APP_SECRET=${APP_SECRET}
    networks:
      - roadie-net

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    volumes:
      - ./back:/app:ro
      - ./back/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - roadie-net

  frontend:
    image: node:26-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    # ports:
    #   - "5173:5173"
    networks:
      - roadie-net
      - lefrigo-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.roadie.rule=Host(`roadie.le-frigo.fr`)
      - traefik.http.routers.roadie.entrypoints=websecure
      - traefik.http.routers.roadie.tls=true
      - traefik.http.routers.roadie.tls.certresolver=myresolver
      - traefik.http.routers.roadie.service=roadie-svc
      - traefik.http.services.roadie-svc.loadbalancer.server.port=5173

networks:
  roadie-net:
    name: roadie-net
  lefrigo-net:
    external: true