services:
  roadie:
    image: roadie:latest
    container_name: roadie
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   APP_ENV: ${APP_ENV:-prod}
    environment:
      # APP_ENV: ${APP_ENV:-prod}
      APP_SECRET: mysecret
      DB_NAME: roadie
      DB_USER: roadie_user
      DB_PASSWORD: roadie_password
      DB_PORT: 5432
      DB_HOST: ${DB_HOST:-roadie-db}
    ports:
      - "8080:80"
    depends_on:
      - roadie-db
    networks:
      - roadie-net

  roadie-db:
    image: postgres:16-alpine
    container_name: roadie-db
    environment:
      POSTGRES_DB: roadie
      POSTGRES_USER: roadie_user
      POSTGRES_PASSWORD: roadie_password
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - roadie-net

networks:
  roadie-net:
    name: roadie-net

volumes:
  database_data:
