services:
  php-fpm:
    build:
      target: dev
    volumes:
      - ./back:/app
      - ./back/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

  frontend:
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - WATCHPACK_POLLING=true

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - roadie-net

volumes:
  database_data: