services:
  php-fpm:
    build:
      context: ./back
      target: base
    env_file:
      - .env
    networks:
      - roadie-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      - ./back:/app:ro
      - ./back/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - roadie-net

  frontend:
    image: node:26-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - roadie-net

networks:
  roadie-net:
    name: roadie-net