<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630213015 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE event ADD title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE notification ADD title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE notification ADD description TEXT NOT NULL');
        $this->addSql('ALTER TABLE notification ADD unread BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE notification ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE file');
        $this->addSql('ALTER TABLE event DROP title');
        $this->addSql('ALTER TABLE notification DROP title');
        $this->addSql('ALTER TABLE notification DROP description');
        $this->addSql('ALTER TABLE notification DROP unread');
        $this->addSql('ALTER TABLE notification DROP created_at');
    }
}
