<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630212306 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE context (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, style VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, music_brainz_artist_id VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) DEFAULT NULL, venue_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7A7FF9380 ON event (venue_id_id)');
        $this->addSql('CREATE TABLE event_context (event_id INT NOT NULL, context_id INT NOT NULL, PRIMARY KEY (event_id, context_id))');
        $this->addSql('CREATE INDEX IDX_670A2CD171F7E88B ON event_context (event_id)');
        $this->addSql('CREATE INDEX IDX_670A2CD16B00C1CF ON event_context (context_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, ico_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, nickname VARCHAR(255) DEFAULT NULL, birthdate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email_verified BOOLEAN NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_context (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id_id INT NOT NULL, context_id_id INT NOT NULL, role_id_id INT NOT NULL, permission_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA509B749D86650F ON user_context (user_id_id)');
        $this->addSql('CREATE INDEX IDX_BA509B742E53F229 ON user_context (context_id_id)');
        $this->addSql('CREATE INDEX IDX_BA509B7488987678 ON user_context (role_id_id)');
        $this->addSql('CREATE INDEX IDX_BA509B74A9C3F324 ON user_context (permission_id_id)');
        $this->addSql('CREATE TABLE user_param (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, theme VARCHAR(255) NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_463887D19D86650F ON user_param (user_id_id)');
        $this->addSql('CREATE TABLE venue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, contact_name VARCHAR(255) NOT NULL, contact_phone_number VARCHAR(255) NOT NULL, contact_email VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7A7FF9380 FOREIGN KEY (venue_id_id) REFERENCES venue (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_context ADD CONSTRAINT FK_670A2CD171F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_context ADD CONSTRAINT FK_670A2CD16B00C1CF FOREIGN KEY (context_id) REFERENCES context (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_context ADD CONSTRAINT FK_BA509B749D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_context ADD CONSTRAINT FK_BA509B742E53F229 FOREIGN KEY (context_id_id) REFERENCES context (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_context ADD CONSTRAINT FK_BA509B7488987678 FOREIGN KEY (role_id_id) REFERENCES role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_context ADD CONSTRAINT FK_BA509B74A9C3F324 FOREIGN KEY (permission_id_id) REFERENCES permission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_param ADD CONSTRAINT FK_463887D19D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7A7FF9380');
        $this->addSql('ALTER TABLE event_context DROP CONSTRAINT FK_670A2CD171F7E88B');
        $this->addSql('ALTER TABLE event_context DROP CONSTRAINT FK_670A2CD16B00C1CF');
        $this->addSql('ALTER TABLE user_context DROP CONSTRAINT FK_BA509B749D86650F');
        $this->addSql('ALTER TABLE user_context DROP CONSTRAINT FK_BA509B742E53F229');
        $this->addSql('ALTER TABLE user_context DROP CONSTRAINT FK_BA509B7488987678');
        $this->addSql('ALTER TABLE user_context DROP CONSTRAINT FK_BA509B74A9C3F324');
        $this->addSql('ALTER TABLE user_param DROP CONSTRAINT FK_463887D19D86650F');
        $this->addSql('DROP TABLE context');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_context');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_context');
        $this->addSql('DROP TABLE user_param');
        $this->addSql('DROP TABLE venue');
    }
}
