name: CI Roadie Monorepo

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  # ==========================================
  # PIPELINE BACKEND (Symfony)
  # ==========================================
  back-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_pgsql, zip
          coverage: none

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v5
        with:
          path: back/vendor
          key: ${{ runner.os }}-back-vendor-${{ hashFiles('back/composer.lock') }}

      - name: Composer Install
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: |
          cp .env.dist .env
          composer install --no-progress --prefer-dist --optimize-autoloader

  back-tests:
    needs: back-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Restore Vendor
        uses: actions/cache@v5
        with:
          path: back/vendor
          key: ${{ runner.os }}-back-vendor-${{ hashFiles('back/composer.lock') }}
          fail-on-cache-miss: true

      - name: Run Linters & Tests
        run: |
          php bin/console lint:yaml config
          php bin/console lint:twig templates
          vendor/bin/phpunit

  back-docker:
    needs: back-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Back Production Image
        run: docker build -f back/Dockerfile --target prod -t roadie-back:latest ./back


  # ==========================================
  # PIPELINE FRONTEND (React / Vite)
  # ==========================================
  front-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v5
        with:
          path: front/node_modules
          key: ${{ runner.os }}-front-modules-${{ hashFiles('front/package-lock.json') }}

      - name: Npm Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  front-tests:
    needs: front-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Restore Node Modules
        uses: actions/cache@v5
        with:
          path: front/node_modules
          key: ${{ runner.os }}-front-modules-${{ hashFiles('front/package-lock.json') }}
          fail-on-cache-miss: true

      - name: Run Lint & Build Test
        run: |
          npm run lint
          npm run build -- --outDir=dist-test # On vérifie juste que le build passe

  front-docker:
    needs: front-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Front Production Image
        run: docker build -f front/Dockerfile --target prod -t roadie-front:latest ./front